//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.22 at 12:04:39 AM CST 
//


package com.nielsen.buzz.outputchecks.visualizer.xml;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the nielsen package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: nielsen
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Report }
     * 
     */
    public Report createReport() {
        return new Report();
    }

    /**
     * Create an instance of {@link Report.DataBase }
     * 
     */
    public Report.DataBase createReportDataBase() {
        return new Report.DataBase();
    }

    /**
     * Create an instance of {@link Report.DataBase.Outlier }
     * 
     */
    public Report.DataBase.Outlier createReportDataBaseOutlier() {
        return new Report.DataBase.Outlier();
    }

    /**
     * Create an instance of {@link Report.DataBase.Outlier.Legacy }
     * 
     */
    public Report.DataBase.Outlier.Legacy createReportDataBaseOutlierLegacy() {
        return new Report.DataBase.Outlier.Legacy();
    }

    /**
     * Create an instance of {@link Report.DataBase.Outlier.Legacy.Row }
     * 
     */
    public Report.DataBase.Outlier.Legacy.Row createReportDataBaseOutlierLegacyRow() {
        return new Report.DataBase.Outlier.Legacy.Row();
    }

    /**
     * Create an instance of {@link Report.DataBase.Outlier.CIP }
     * 
     */
    public Report.DataBase.Outlier.CIP createReportDataBaseOutlierCIP() {
        return new Report.DataBase.Outlier.CIP();
    }

    /**
     * Create an instance of {@link Report.DataBase.Outlier.CIP.Row }
     * 
     */
    public Report.DataBase.Outlier.CIP.Row createReportDataBaseOutlierCIPRow() {
        return new Report.DataBase.Outlier.CIP.Row();
    }

    /**
     * Create an instance of {@link Report.DataBase.Outlier.Row }
     * 
     */
    public Report.DataBase.Outlier.Row createReportDataBaseOutlierRow() {
        return new Report.DataBase.Outlier.Row();
    }

    /**
     * Create an instance of {@link Report.DataBase.Outlier.Header }
     * 
     */
    public Report.DataBase.Outlier.Header createReportDataBaseOutlierHeader() {
        return new Report.DataBase.Outlier.Header();
    }

    /**
     * Create an instance of {@link Report.DataBase.Dimension }
     * 
     */
    public Report.DataBase.Dimension createReportDataBaseDimension() {
        return new Report.DataBase.Dimension();
    }

    /**
     * Create an instance of {@link Report.DataBase.Dimension.Legacy }
     * 
     */
    public Report.DataBase.Dimension.Legacy createReportDataBaseDimensionLegacy() {
        return new Report.DataBase.Dimension.Legacy();
    }

    /**
     * Create an instance of {@link Report.DataBase.Dimension.Legacy.Row }
     * 
     */
    public Report.DataBase.Dimension.Legacy.Row createReportDataBaseDimensionLegacyRow() {
        return new Report.DataBase.Dimension.Legacy.Row();
    }

    /**
     * Create an instance of {@link Report.DataBase.Dimension.Legacy.Columns }
     * 
     */
    public Report.DataBase.Dimension.Legacy.Columns createReportDataBaseDimensionLegacyColumns() {
        return new Report.DataBase.Dimension.Legacy.Columns();
    }

    /**
     * Create an instance of {@link Report.DataBase.Dimension.CIP }
     * 
     */
    public Report.DataBase.Dimension.CIP createReportDataBaseDimensionCIP() {
        return new Report.DataBase.Dimension.CIP();
    }

    /**
     * Create an instance of {@link Report.DataBase.Dimension.CIP.Row }
     * 
     */
    public Report.DataBase.Dimension.CIP.Row createReportDataBaseDimensionCIPRow() {
        return new Report.DataBase.Dimension.CIP.Row();
    }

    /**
     * Create an instance of {@link Report.DataBase.Dimension.CIP.Columns }
     * 
     */
    public Report.DataBase.Dimension.CIP.Columns createReportDataBaseDimensionCIPColumns() {
        return new Report.DataBase.Dimension.CIP.Columns();
    }

    /**
     * Create an instance of {@link Report.DataBase.Outlier.Legacy.Row.Field }
     * 
     */
    public Report.DataBase.Outlier.Legacy.Row.Field createReportDataBaseOutlierLegacyRowField() {
        return new Report.DataBase.Outlier.Legacy.Row.Field();
    }

    /**
     * Create an instance of {@link Report.DataBase.Outlier.CIP.Row.Field }
     * 
     */
    public Report.DataBase.Outlier.CIP.Row.Field createReportDataBaseOutlierCIPRowField() {
        return new Report.DataBase.Outlier.CIP.Row.Field();
    }

    /**
     * Create an instance of {@link Report.DataBase.Outlier.Row.Field }
     * 
     */
    public Report.DataBase.Outlier.Row.Field createReportDataBaseOutlierRowField() {
        return new Report.DataBase.Outlier.Row.Field();
    }

    /**
     * Create an instance of {@link Report.DataBase.Outlier.Header.Column }
     * 
     */
    public Report.DataBase.Outlier.Header.Column createReportDataBaseOutlierHeaderColumn() {
        return new Report.DataBase.Outlier.Header.Column();
    }

    /**
     * Create an instance of {@link Report.DataBase.Dimension.Legacy.Row.Field }
     * 
     */
    public Report.DataBase.Dimension.Legacy.Row.Field createReportDataBaseDimensionLegacyRowField() {
        return new Report.DataBase.Dimension.Legacy.Row.Field();
    }

    /**
     * Create an instance of {@link Report.DataBase.Dimension.Legacy.Columns.Column }
     * 
     */
    public Report.DataBase.Dimension.Legacy.Columns.Column createReportDataBaseDimensionLegacyColumnsColumn() {
        return new Report.DataBase.Dimension.Legacy.Columns.Column();
    }

    /**
     * Create an instance of {@link Report.DataBase.Dimension.CIP.Row.Field }
     * 
     */
    public Report.DataBase.Dimension.CIP.Row.Field createReportDataBaseDimensionCIPRowField() {
        return new Report.DataBase.Dimension.CIP.Row.Field();
    }

    /**
     * Create an instance of {@link Report.DataBase.Dimension.CIP.Columns.Column }
     * 
     */
    public Report.DataBase.Dimension.CIP.Columns.Column createReportDataBaseDimensionCIPColumnsColumn() {
        return new Report.DataBase.Dimension.CIP.Columns.Column();
    }

}
